### ISSUE TITLE
Can I contribute or should I fork?

### ISSUE THREAD

**Issue by wimrijnders** [mn416/QPULib#14]
@mn416 I would love to contribute to the project. It is in my opinion the best thing on github for GPU programming on the Raspberry Pi and I would really like to take it further. I personally have an interest in making GPU programming for the RPi more accessible, and I believe that any changes I make will benefit everybody.

However, I have the impression that there is no active maintenance on `QPULib`, despite the observation that there was  some activity a month ago.  In addition, I have had no feedback from you about previous requests on this. I am now tempted to just fork the project and take it from there - but I would really prefer that it stays in its original place.

So, for your understanding, this is what I want to do as a first step:

- Raise the makefile 1 level and expand it
- Add some documentation for better understanding
- Rearrange current documentation
- Add doc generation, notably with `doxygen`
- Add unit tests with the `CATCH` framework

All this is to make it better usable for other developers, in particular me. Note that I do not intend to change the working of the code now, perhaps some rearrangement for usage in the unit tests.

I would severely appreciate some feedback on this. Can you agree that these are worthwhile additions? I prefer to avoid maintaining a separate fork if at all necessary.

Hoping to hear from you.

**Comment by mn416** [comment]
Hi @wimrijnders, thanks for your comments!

I will try to review pull requests on all aspects of the library, and the areas you have suggested sound like good areas for improvement.

In general, I'd rather not introduce any new dependencies into the project, so if the `CATCH` framework you mention needs to be installed before QPULib can be used, then I would find that off-putting, unless it can be done in a way that the new dependencies are not mandatory.

It is true that I don't have much time for QPULib at the moment, but if I see issues I can help with then do generally try to offer suggestions.

I'm sorry that I didn't respond to the issue you mentioned.  Actually, I didn't see it until now.  It seems I only receive notifications when given an explicit mention.

**Comment by wimrijnders** [comment]
Thanks for answering! Happy that you're still present here.

Overall I'm very impressed by what you made here. It is by far the most advanced thing on `github` for GPU programming on RPi, and I've scanned them *all*. However, it still has an academic feel to it; my first goal, implicated by the list above, is to raise the level of robustness and make the entry easier for developers - which of course includes myself.

----

> I'd rather not introduce any new dependencies into the project,

What I do in my projects, is make `CATCH` part of it, so there won't be any external dependencies. It's defined as a bunch of header files, so there's not much point in keeping it separate anyway. The downside is that those files easily outnumber the size of the current project, so it will look a little lopsided.

`doxygen`, though, is much too big for that, and I intend to add usage of it as you describe, namely if available it will be used, otherwise doc generation will be skipped.


> It is true that I don't have much time for QPULib at the moment

I am sympathetic to that, that's perfectly fine. For now, I am hoping you can review the pull requests I throw at you. And perhaps answer any questions along the way. I hope that will not place much strain on your time.

----
Since you are responsive, I'll start out by setting up a new makefile which retains the current functionality. PR is forthcoming!

**Comment by wimrijnders** [comment]
@mn416 I will honestly say that making a good makefile for the project was harder than I thought. I think I'm trying to do too much in one go; I will attempt a more evolutionary approach instead.

**Comment by wimrijnders** [comment]
I think we're on a roll here. I'll just transplant the list above to my TODO and this issue too can close.
