### ISSUE TITLE
Request: Add a Development branch

### ISSUE THREAD

**Issue by wimrijnders** [mn416/QPULib#16]
@mn416 Please add a branch called `development` to the repo. This allows us to add changes to a new version while keeping the current version stable.

In particular, this shields from awry things happening when PR's have unexpected side-effects.

Related, is there a version numbering present? If not, now would be a good time to add it.

**Comment by mn416** [comment]
> Please add a branch called development to the repo. This allows us to add changes to a new version while keeping the current version stable.

Good idea, done!

> Related, is there a version numbering present? If not, now would be a good time to add it.

Not at present.  If you like, we can use semantic versioning and call the current version 1.0.0.

**Comment by wimrijnders** [comment]
:+1:  But don't do 1.0.0, it's considered presumptuous. I suggest 0.0.0, but feel free to do a guesstimate.

Location: how about for the time being at the top of the README.md? As long as it's a single location.

**Comment by wimrijnders** [comment]
Ok great! Will you do the honors of putting up `v0.1.0` on the README then? This is sort of like christening a ship with a bottle.

**Comment by mn416** [comment]
Done!  Rebased the `development` branch too...

**Comment by wimrijnders** [comment]
Got it! Thanks for the quick handling, onwards to the next issue!
