### ISSUE TITLE
Request: change name of dir 'Tests' to 'Examples'

### ISSUE THREAD

**Issue by wimrijnders** [mn416/QPULib#22]
The reason for this is:

- I believe the name is a misnomer, the directory contains example programs (perhaps excluding `AutoTest`).
- My intention is to add unit tests in due time, and putting it into any other directory than `Tests` will be confusing.

Please tell me if you agree to this change, I will make it myself.

**Comment by mn416** [comment]
Absolutely right, it should be `Examples` not `Tests`, except for `AutoTest`!

**Comment by wimrijnders** [comment]
Done in #31
