### ISSUE TITLE
Makefile wrong -D flag

### ISSUE THREAD

**Issue by Joonho365Han** [mn416/QPULib#4]
The QPU_MODE should be enabled if QPU>1 for make argument.
Current Makefile sets -DEMULATION_MODE if QPU>1.

**Comment by mn416** [comment]
Hi @Joonho365Han ,

Thanks for the report.

If I build with `make QPU=1 target` then `QPU_MODE` is enabled and `EMULATION_MODE` is disabled.  If I build with `make target` then `EMULATION_MODE` is enabled and `QPU_MODE` is disabled.  Is this not sufficient?

This is the second report I've received about the `QPU` makefile option, so I'm starting to think I'm missing something!

**Comment by Joonho365Han** [comment]
Oh I See! So the value "1" refers to "true" for enabling QPU. I thought it meant "number of QPUs to be used."
Sorry for the confusion.
