### ISSUE TITLE
Question: How do you mark a program as threadable?

### ISSUE THREAD

**Issue by wimrijnders** [mn416/QPULib#41]
I encountered the following in the `VideoCore IV` reference on page 21: 

> For 3D fragment shader use, each QPU can execute two separate program threads if both the fragment shader programs are marked as *threadable*.

I'm wondering how you can mark a program as 'threadable'? Are there special instructions for that? I can't seem to find anything about it in the document, nor on google.

**Comment by Terminus-IMRC** [comment]
It seems that the "threadable" flag can be set only via control list (c.f. Table 45 on p.78 and Table 47 on p.80).

FYI there is a better place to ask such questions: https://www.raspberrypi.org/forums/viewforum.php?f=72

**Comment by wimrijnders** [comment]
@Terminus-IMRC thanks for responding. That brings me one step closer to enlightment.

I scanned the forum you linkes to, 'bare metal'. It's a bunch of people doing really low-level stuff on the RPi, it's pretty impressive. And intimidating!

**Comment by Terminus-IMRC** [comment]
... so could you please close this issue and https://github.com/mn416/QPULib/issues/33 ?

**Comment by wimrijnders** [comment]
Sorry, are you an administrator here? I didn't realize.

Not closing #33 until the hardware lookup for slices and num qpu's has been merged.

**Comment by Terminus-IMRC** [comment]
No, I'm not. I'm just a passer-by. Sorry for snooping...

**Comment by wimrijnders** [comment]
OK, clear. You are however a very knowledgeable passer-by which I would like to be on good terms with. No harm intended.
