### ISSUE TITLE
Summation of vector elements using QPULib

### ISSUE THREAD

**Issue by rimitalahiri** [mn416/QPULib#5]
I want to perform summation of elements of a vector using QPULib, is it possible to extract a scalar from a vector using QPULib, if so how can we implement that. An example will be extremely helpful.
Please help @mn416 .

**Comment by schramm** [comment]
Hi  @mn416 and @rimitalahiri, 
I am also trying to perform the summation of elements of a vector. Is there any instruction  (similar to the instruction "store")  in the QPULib that performs this task?

**Comment by mn416** [comment]
Hi @rimitalahiri and @schramm,

As far as I know, this is not something you can do very efficiently on the QPUs.  Here is the most efficient way I can think of to sum a vector `v`:

```
Int v;
...
v = v + rotate(8, v);
v = v + rotate(4, v);
v = v + rotate(2, v);
v = v + rotate(1, v);
```

I'm not aware of a way to extract a "scalar" on the QPUs (it only has vector registers), other than by writing it to memory and loading it into a scalar ARM core register.

**Comment by NazaninDelazimi** [comment]
Hi,
I use this code but receive this error what is the problem ?
D.cpp:13:20: error: call of overloaded ‘rotate(int, Int&)’ is ambiguous
 v = v + rotate(1, v);
                    ^
In file included from ../Lib/QPULib.h:4:0,
                 from ID.cpp:1:
../Lib/Source/Int.h:61:9: note: candidate: IntExpr rotate(IntExpr, IntExpr)
 IntExpr rotate(IntExpr a, IntExpr b);
         ^~~~~~
../Lib/Source/Int.h:62:11: note: candidate: FloatExpr rotate(FloatExpr, IntExpr)
 FloatExpr rotate(FloatExpr a, IntExpr b);
thank you.
